// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY9jQU4tyAQYR5FIzs2ggZHR4JuhDL4is',
    appId: '1:416525720358:web:5b80c0fa50f85062edffe7',
    messagingSenderId: '416525720358',
    projectId: 'todo-162ab',
    authDomain: 'todo-162ab.firebaseapp.com',
    storageBucket: 'todo-162ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRg8jBC6_SQk9MTMhPMlEKGTpYbh2LIAE',
    appId: '1:416525720358:android:5141694ee93234beedffe7',
    messagingSenderId: '416525720358',
    projectId: 'todo-162ab',
    storageBucket: 'todo-162ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB99kz2diGUBNWJu-Q9GTmXyOtXCRBGr_Y',
    appId: '1:416525720358:ios:ddbb489556dd9797edffe7',
    messagingSenderId: '416525720358',
    projectId: 'todo-162ab',
    storageBucket: 'todo-162ab.appspot.com',
    iosClientId: '416525720358-6vi5s01o78lmariv9pc3filq508v0p0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB99kz2diGUBNWJu-Q9GTmXyOtXCRBGr_Y',
    appId: '1:416525720358:ios:ddbb489556dd9797edffe7',
    messagingSenderId: '416525720358',
    projectId: 'todo-162ab',
    storageBucket: 'todo-162ab.appspot.com',
    iosClientId: '416525720358-6vi5s01o78lmariv9pc3filq508v0p0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
